<div class="swiper-container banner">
    <div class="swiper-wrapper">
        <div class="swiper-slide" style="background-image:url('../img/banner.png')">
            <a href="banner-detail.html">
                <h2 class="title">科技，让金融更开放</h2>
                <p class="desc">—— 快速接入金融服务流程 ——</p>
                <span class="contact-btn consultation">咨询合作</span>
            </a>
        </div>
    </div>
    <div class="pagination"></div>
    <div class="prev"></div>
    <div class="next"></div>
</div>