<div class="counsel">
    <div class="counsel-cover hide"></div>
    <div id="counsel-container" class="counsel-container hide">
        <div class="counsel-form-con">
            <h1>咨询合作</h1>
            <a href="javascript:;" class="closebt">
                <img src="../img/counsel-close.png">
            </a>
            <div class="counsel-content">
               <ul class="reg-bd">
                                  <li>
                                      <label for="company_name">公司</label>
                                      <div class="ui-input">
                                          <input autocomplete="off" type="text" class="i-text" id="company_name">
                                      </div>
                                  </li>
                                  <li>
                                      <label for="user_name">姓名</label>
                                      <div class="ui-input">
                                          <input autocomplete="off" type="text" class="i-text" id="user_name"/>
                                      </div>
                                  </li>
                                  <li>
                                      <label for="phone_number">手机号</label>
                                      <div class="ui-input">
                                          <input autocomplete="off" type="text" class="i-text" id="phone_number">
                                      </div>
                                  </li>
                                  <li>
                                      <label for="sms_code">短信验证码</label>
                                      <div class="ui-input">
                                          <input type="text" class="i-text" id="sms_code"/>
                                      </div>
                                      <span class="span-vercode">获取验证码</span>
                                  </li>
                                  <li class='error-code-li'>
                                      <p class="error-code"></p>
                                  </li>
                              </ul>
                              <textarea placeholder="问题描述" name="name" rows="5" cols="36" id="problem_description"></textarea>
                              <p class="error"></p>
                              <button id="submit">提 交</button>
            </div>
        </div>
        <div class="counsel-success hide">
            <div class="counsel-success-in">
                <a href="javascript:;" class="closebt closebt-success">
                    <img src="../img/counsel-close.png">
                </a>
                <img src="../img/counsel-ok.png" alt="" />
                <h1>提交成功</h1>
                <h2>专业售前人员会在1个工作日内与您联系，祝您工作顺利！</h2>
            </div>
        </div>
            <div class="counsel-loading hide">
                <div class="counsel-loading-in">
                    <h2>正在提交，请稍后...</h2>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
    </div>
</div>
