<footer>
    <div class="footer-hd" style="background: url('//img12.360buyimg.com/wympay/jfs/t3085/276/4096237471/15786/f2070898/57ff5d8eNb164bdfa.jpg') center no-repeat"></div>
    <div class="footer">
        <div class="container">
            <p class="links">
                <a href="http://www.jd.com" target="_blank">京东商城</a>｜
                <a href="http://jr.jd.com" target="_blank">京东金融</a>｜
                <a href="http://www.jcloud.com" target="_blank">京东云</a>｜
                <a href="http://smart.jd.com" target="_blank">京东智能</a>｜
                <a href="http://jzt.jd.com/gw/" target="_blank">京准通</a>｜
                <a href="http://wxlink.jd.com" target="_blank">京东万象</a>｜
                <a href="about.html" target="_blank">关于我们</a>
            </p>
            <p class="copyright">Copyright &copy; 2004-2016 京东JD.com 版权所有</p>
        </div>
    </div>
</footer>

<script type="text/javascript" src="//tajs.qq.com/stats?sId=59053717" charset="UTF-8"></script>
<script type="text/javascript" src="//pingjs.qq.com/h5/stats.js" name="MTAH5" sid="500326688" cid="500332905" opts="{&quot;senseHash&quot;:false,&quot;autoReport&quot;:false,&quot;performanceMonitor&quot;:false}" ></script>