<header class="header">
    <div class="user-bar">
        <p class="container">
            <a href="http://www.baidu.com" id="logout">登录</a>
            <a href="http://ft.jd.com">注册</a>
        </p>
    </div>
    <div class="container">
        <div class="logo">
            <a href="index.html">
                <img src="//img14.360buyimg.com/wympay/jfs/t3748/300/108123672/4451/c42d7358/57ff5e34N6e63c570.png" alt="京东金融企业服务平台"/>
            </a>
        </div>
        <nav class="nav">
            <ul>
                <li>
                    <a href="index.html">首页</a>
                </li>
                <li>
                    <a href="product-intro.html">产品介绍</a>
                </li>
                <li class="dropdown">
                    <a href="javascript:;">解决方案</a>
                    <div class="sub-nav">
                        <ul class="container">
                            <li>
                                <a data-icon="&#xe604;" href="finance-solution.html">金融</a>
                            </li>
                            <li>
                                <a data-icon="&#xe602;" href="education-solution.html">教育</a>
                            </li>
                            <li>
                                <a data-icon="&#xe601;" href="hr-solution.html">HR服务平台</a>
                            </li>
                            <li>
                                <a data-icon="&#xe603;" href="food-solution.html">餐饮商超</a>
                            </li>
                            <li>
                                <a data-icon="&#xe600;" href="fastgoods-solution.html">快消品</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a href="http://172.24.4.16:8088/auth?redirect=http%3A%2F%2F172.24.4.16%3A8888%2F">ABS投资人平台</a>
                </li>
                <!--
                <li>
                    <a href="document.html">开发文档</a>
                </li>
                <li>
                    <a href="about.html">关于我们</a>
                </li>
                -->
            </ul>
        </nav>
    </div>
</header>
