<nav id="slideNav">
    <ul>
        <li><a href="#1.1">接口接入必读</a></li>
        <li><a href="#2.1">企业账户类</a></li>
        <li class="sub-nav"><a href="#2.1">企业帐户注册</a></li>
        <li class="sub-nav"><a href="#2.2">企业账户信息查询</a></li>
        <li class="sub-nav"><a href="#2.3">企业实名认证（http）</a></li>
        <li><a href="#3.1">H5组件通用调用</a></li>
        <li><a href="#4.1">个人账户类</a></li>
        <li class="sub-nav"><a href="#4.1">个人账户注册</a></li>
        <li class="sub-nav"><a href="#4.2">个人账户信息查询</a></li>
        <li><a href="#5.1">企业支付类</a></li>
        <li class="sub-nav"><a href="#5.1">余额收单</a></li>
    </ul>
    <a class="download-btn" href="#6.1"> 接口文档下载</a>
</nav>